import type { Repository } from "./types"

export const mockRepos: Repository[] = [
  {
    id: "1",
    name: "polkadot-js-api",
    owner: "alice",
    description: "JavaScript API for interacting with Polkadot and Substrate nodes",
    stars: 245,
    forks: 87,
    lastUpdated: "2 days ago",
    tags: ["api", "javascript", "substrate"],
    ipfsHash: "QmZ4tDuvesekSs4qM5ZBKpXiZGun7S2CYtEZRB3DYXkjGx",
    nftId: "NFT-001",
  },
  {
    id: "2",
    name: "substrate-node-template",
    owner: "bob",
    description: "A template for building custom Substrate nodes",
    stars: 189,
    forks: 56,
    lastUpdated: "5 days ago",
    tags: ["substrate", "blockchain", "template"],
    ipfsHash: "QmULKig5Fxrs2uC5oBBKPNhJawxbq8tGsxYTc9mZQVtpSm",
    nftId: "NFT-002",
  },
  {
    id: "3",
    name: "ink-examples",
    owner: "charlie",
    description: "Example smart contracts written in ink!",
    stars: 132,
    forks: 41,
    lastUpdated: "1 week ago",
    tags: ["ink", "smart-contracts", "wasm"],
    ipfsHash: "QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG",
    nftId: "NFT-003",
  },
  {
    id: "4",
    name: "polkaforge-cli",
    owner: "dave",
    description: "Command-line interface for PolkaForge",
    stars: 78,
    forks: 23,
    lastUpdated: "3 days ago",
    tags: ["cli", "tools", "git"],
    ipfsHash: "QmTkzDwWqPbnAh5YiV5VwcTLnGdwSNsNTn2aDxdXBFca7D",
    nftId: "NFT-004",
  },
  {
    id: "5",
    name: "nft-marketplace",
    owner: "eve",
    description: "NFT marketplace built on Polkadot",
    stars: 156,
    forks: 34,
    lastUpdated: "4 days ago",
    tags: ["nft", "marketplace", "defi"],
    ipfsHash: "QmRA3NWM82ZGynMbYzAgYTSXCVM14Wx1RZ8fKP42G6gjgj",
    nftId: "NFT-005",
  },
  {
    id: "6",
    name: "polkadot-staking-dashboard",
    owner: "frank",
    description: "Dashboard for Polkadot staking operations",
    stars: 112,
    forks: 29,
    lastUpdated: "6 days ago",
    tags: ["staking", "dashboard", "defi"],
    ipfsHash: "QmSgvgwxZGaBLqkGyLcyN7xhALZe4P1RLw5vY7FWEjkZWg",
    nftId: "NFT-006",
  },
]
